### ISSUE TITLE
Custom form

### ISSUE THREAD

**Issue by lormayna** [true3dco/splashgen#2]
Is there a way to add a custom form?

**Comment by traviskaufman** [comment]
Not yet, but this is definitely something we want to add in! Can you tell me a bit more about what information you'd want to get and where you'd want the form submission to go?

**Comment by Dohva** [comment]
I've run into an issue with github pages integration where the image 'logo-default.png' shows up as an empty box. I've followed your guide, changing only the text values. It builds without errors otherwise. Following the src in the image tag successfully servers the image.

Partial screenshot attached. 
![image](https://user-images.githubusercontent.com/26593237/119627143-34d21400-be0c-11eb-810c-f26b362e3e6c.png)

**Comment by lormayna** [comment]
I was thinking about creating a simple form and send the result to a POST
HTTP endpoint (for example hosted on AWS Lambda, Azure Cloud function or
Vercel).
I know that I can make it embedding HTML, but having something already
baked will be great

Il mar 25 mag 2021, 17:13 Travis Kaufman ***@***.***> ha
scritto:

**Comment by traviskaufman** [comment]
Something like this maybe?

```python
site.call_to_action = Form(
  endpoint="https://my.endpoint/signup",
  inputs={
    "firstname": TextInput("First Name", required=True),
    "lastname": TextInput("Last Name", required=True),
    "email": EmailInput("Email Address", required=True),
    "role": SelectInput("Your Role", options=["CEO/Founder", "Engineer", "Finance", "Other"]),
  },
  submit_text="Join our waitlist")
```

**Comment by lormayna** [comment]
Yes, this will be great 😊

Il mer 26 mag 2021, 18:48 Travis Kaufman ***@***.***> ha
scritto:

**Comment by traviskaufman** [comment]
Should be added in as of v0.0.28! `pip install -U splashgen` 👯 Let me know if you run into any issues!
