### ISSUE TITLE
Error integrating with github pages

### ISSUE THREAD

**Issue by Dohva** [true3dco/splashgen#3]
I've run into an issue with github pages, where it fails to serve the default logo. The path in src successfully points to the image when followed explicitly in another tab, but loads as an empty box on the site. When built locally it also successfully serves the image.

[Link to live page](https://dohva.github.io/RakdamSplash/)
Partial screenshot attached
![image](https://user-images.githubusercontent.com/26593237/119628083-115b9900-be0d-11eb-9893-57b1437c4fdf.png)

**Comment by traviskaufman** [comment]
Thanks so much for reporting! I believe this was fixed in https://github.com/true3dco/splashgen/commit/c24e2bc21a05904ccc230105bbbb8c761c17c65f

Which version of splashgen do you have installed (`pip show splashgen | grep Version`)? If it's < 0.0.26, I believe you can fix this issue by running `pip install -U splashgen` to upgrade. Let me know if that doesn't work!

**Comment by Dohva** [comment]
I was using version 0.0.24, and upgrading to the newest version fixed the issue. Thank you for replying.

**Comment by traviskaufman** [comment]
Excellent! My pleasure 👍🏻 

Btw, the repo looks really interesting. If you wind up writing something about how you are able to use GH actions to publish to GH pages without checking in the build folder, we'd love to include that info in our README.

**Comment by Dohva** [comment]
It actually turned out to be really simple, once I got the hang of GitHub Actions. Just plug the workflow under the 'actions' branch into a repo, and it'll build in the cloud and push the build/ folder to the specified branch.
Feel free to integrate anything from the repo into your readme. I'm happy to do a quick rundown of the process.
